### ISSUE TITLE
Declaring puppetdb::server does not inherit params.pp

### ISSUE THREAD

**Issue by lazarus1331** [puppetlabs/puppetlabs-puppetdb#111]
We have configured the puppetdb::params.pp with the settings for our postgresql server.  When we attempt to install the puppetdb server via declaring puppetdb::server, it does not properly inherit the parameters from params.pp, which results in the following errors:

Notice: /Stage[main]/Puppetdb::Server::Validate_db/Postgresql::Validate_db_connection[validate puppetdb postgres connection]/Exec[validate postgres connection for localhost/puppetdb]/returns: Unable to connect to defined database using: /usr/pgsql-9.3/bin/psql --tuples-only --quiet -h localhost -U puppetdb -p 5432 --dbname puppetdb 
Error: echo 'Unable to connect to defined database using: /usr/pgsql-9.3/bin/psql --tuples-only --quiet -h localhost -U puppetdb -p 5432 --dbname puppetdb ' && false returned 1 instead of one of [0]

**Comment by h0tw1r3** [comment]
`puppetdb::params` can not be "configured" directly, its purpose is to provide reasonable defaults to classes that inherit it. Overrides are done through class parameters on the class that _inherits_ a params class.

puppetdb::server does in fact inherit the puppetdb::params class
