### ISSUE TITLE
Module is broken due to $::is_pe on puppet opensource

### ISSUE THREAD

**Issue by juanbrein** [puppetlabs/puppetlabs-puppetdb#124]
When trying to use this module it complains due to not being able to install pe-puppetdb and pe-puppetdb-terminus.

I think the problem is this line in params.pp:

```
  if $::is_pe {
```

The problem as far as I can see is that $::is_pe is not a bool but a string. 

Possible fix would be something like:

```
if $::is_pe == 'true' {
```

But might be that is better to change the fact and make it return bool which is in stdlib

**Comment by bschonec** [comment]
If this is fixed, can the issue be close as well?
