### ISSUE TITLE
Allow puppetdb module to manage init settings file

### ISSUE THREAD

**Issue by kbarber** [puppetlabs/puppetlabs-puppetdb#32]
(moved from redmine - https://projects.puppetlabs.com/issues/18818)

If I’m reading it right, the init settings file (like /etc/sysconfig/puppetdb on Redhat) is the only way to modify the Java args for PuppetDB. So, this should be managed by the module, too. Am I missing another way to do this in the existing module?

**Comment by h0tw1r3** [comment]
#210 supports customizing java args, and #307 supports customizing the java path.

If more flexibility is needed, please feel free to reopen this issue with additional details.
