### ISSUE TITLE
PE 2.7.0: redeclaring pe-httpd service

### ISSUE THREAD

**Issue by carthik** [puppetlabs/puppetlabs-puppetdb#34]
Using the puppetdb module on a PE-2.7.0 node causes the following error:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Service[pe-httpd] is already declared in file /etc/puppetlabs/puppet/modules/puppetdb/manifests/master/config.pp at line 116; cannot redeclare at /opt/puppet/share/puppet/modules/request_manager/manifests/init.pp:23 on node classroom.puppetlabs.vm

request_manager is a part of Puppet Enterprise, and adds the new "node requests" certificate management feature.

**Comment by h0tw1r3** [comment]
PE no longer uses this module to manage postgresql.
