### ISSUE TITLE
Modules version 7.14.0 not uploaded to the forge

### ISSUE THREAD

**Issue by bigon** [puppetlabs/puppetlabs-puppetdb#381]
Hello,

The last release in the forge is 7.13.0, but here there is a version 7.14.0 tagged.

This version should be uploaded to the forge as 7.13.0 is not installable due to dependency issues

Please upload 7.14.0 to the forge

**Comment by deric** [comment]
@smortex  @bastelfreak Any progress on this?

**Comment by bastelfreak** [comment]
I don't think I've the permission to upload old releases. Please ask Puppet/Perforce. Also we're in the process of releasing 8.0.0.

**Comment by edrude** [comment]
For what it's worth I have been running 7.14.0 in production for a few months now so that I could bump the puppetlabs/stdlib version. Looking forward to 8.0.0!

In case it helps anyone:
```
mod 'puppetdb',
  :git => 'https://github.com/puppetlabs/puppetlabs-puppetdb.git',
  :tag => '7.14.0'
```

**Comment by abegosum** [comment]
I would like to see this as well.  I'm currently pinned to the github tag, but would prefer as  many of my modules come from forge as possible for consistency.

**Comment by h0tw1r3** [comment]
Now that [release 8.0.0](https://github.com/puppetlabs/puppetlabs-puppetdb/releases/tag/v8.0.0) is out, is this still needed? It's a bit of a pain, but I could try to make it happen.

**Comment by bigon** [comment]
I guess for consistency/correctness would be good to have it.

But if it's that complex todo, the git workaround might be good enough

my 2¢

**Comment by smortex** [comment]
@h0tw1r3 given version 8.x depends on postgresql 10.x (#402) and postgresql 10.x is broken when you setup a custom locale (https://github.com/puppetlabs/puppetlabs-postgresql/pull/1564), maybe it's worth uploading the missing release because some people are currently blocked on 7.x?

**Comment by h0tw1r3** [comment]
Published
https://forge.puppet.com/modules/puppetlabs/puppetdb/readme
