### ISSUE TITLE
Support puppetlabs-postgresql version 10

### ISSUE THREAD

**Issue by maureen-lawless** [puppetlabs/puppetlabs-puppetdb#393]
Could support for puppetlabs-postgresql version 10 be added?

In the latest version of puppetlabs-puppetdb 7.14.0, versions < 10.0.0 are supported.

I'd like to use Puppet 8 - which is supported by puppetlabs-puppetdb, however when looking through the dependency chain:

puppetlabs-puppetdb requires puppetlabs-postgresql <=10 
The latest version < 10 => 9.2.0 requires systemd less than < 6.0.0
The latest version of systemd < 6.0.0  => 5.2.0 states that it requires some version of Puppet 7  Puppet >= 7.0.0 < 8.0.0, not Puppet 8

So there is a mismatch here.

**Comment by gcoxmoz** [comment]
As of 697d79a1936a34349b2a03806ac2082a6ae535f9 this is done; you're probably in a situation of "a dot release hasn't happened since then".

**Comment by maureen-lawless** [comment]
Hi @gcoxmoz,

Is a release of https://github.com/puppetlabs/puppetlabs-puppetdb/commit/697d79a1936a34349b2a03806ac2082a6ae535f9 imminent?

**Comment by gcoxmoz** [comment]
Beats me, I don't work here.

**Comment by bschonec** [comment]
I'm running postgresql16-16.2-1PGDG.rhel8.x86_64 on RHEL and I've not experienced any issues with PuppetDB on Postgres 16.  Is there a historical reason that the supported version of postgres is so old?

**Comment by h0tw1r3** [comment]
[Release 8.0.0](https://github.com/puppetlabs/puppetlabs-puppetdb/releases/tag/v8.0.0) is out and defaults to Postgres 14.
The mentioned module dependencies should be resolved.
