### ISSUE TITLE
Install fails if postgres_version is not set

### ISSUE THREAD

**Issue by d1nuc0m** [puppetlabs/puppetlabs-puppetdb#396]
## Describe the Bug
Automatic setup of PostgreSQL does not work unless an updated version is specified

## Expected Behavior
Minimal install works:

```puppet
class { 'puppetdb':
}
```

## Steps to Reproduce
1. Try a minimal install
```puppet
class { 'puppetdb':
}
``` 
PostgreSQL install fails as packages are not in the repositories

2. Specify a supported PostgreSQL version (>= 12)
```puppet
class { 'puppetdb':
  postgres_version  => '13',
}
```
and install succeeds

## Environment
 - Version [7.13.0]
 - Platform [EL 9.x]

## Additional Context
The most up-to-date puppetlabs-postgresql supported by this module (8.3.0) defaults to postgres 11, as it was supported at release time. [Now it is EOL](https://www.postgresql.org/support/versioning/), so packages have been removed from the repositories and install fails

**Comment by h0tw1r3** [comment]
This was fixed in #379 and part of release [8.0.0](https://github.com/puppetlabs/puppetlabs-puppetdb/releases/tag/v8.0.0)
