### ISSUE TITLE
Error 'has no parameter named port'

### ISSUE THREAD

**Issue by StephaneGerardVUB** [puppetlabs/puppetlabs-puppetdb#401]
## Describe the Bug
When trying to compile the catalog with puppetdb 8.0.0 and postgresql 9.2.0, it fails with error 'has no parameter named 'port'.

The error is located in file /etc/puppetlabs/code/environments/prod/modules/puppetdb/manifests/database/postgresql.pp at line 149

**Comment by smortex** [comment]
This was changed in #392 and depends on https://github.com/puppetlabs/puppetlabs-postgresql/pull/1494

It looks like the bump of the lower bound version requirement for the PostgreSQL module is missing.  I will open a PR to fix it.
