### ISSUE TITLE
installing puppetdb and puppetmaster at the same time fails

### ISSUE THREAD

**Issue by iverberk** [puppetlabs/puppetlabs-puppetdb#43]
I'm trying to create a Puppet manifest that will install the puppetmaster package/service and PuppetDB for me at the same time. It seems this is not possible because of a dependency cycle issue. Basically I want the puppetdb and puppetdb::master::config class to depend on a started puppetmaster service. This however results in a dependency cycle because of the following code: http://pastebin.com/b75MUCsk

The puppetmaster needs to be started to create the certificates which are required by the puppetdb class to create a keystore.

Any suggestions/tips/fixes are welcome since I don't see a proper solution yet. I'm using this manifest file on a clean CentOS 6.4: http://pastebin.com/95tcv1Jj

**Comment by h0tw1r3** [comment]
#250 and #234 should give sufficient control over how and when the puppetserver is restarted.

Additionally, puppetdb will automatically setup ssl on install (executing `puppetdb ssl-setup`) as part of the package post-install scripts.
