### ISSUE TITLE
default location for embedded database violates the FHS

### ISSUE THREAD

**Issue by rendhalver** [puppetlabs/puppetlabs-puppetdb#56]
The default location for the embedded database defaults to /usr/share/puppetdb/db/db
This is the worst place to put this and it violates the LSB and FHS and most sensible defaults for databases.
According to the FHS (the Filesystem Hierarchy Standard) /usr/share is for Architecture-independent data.

It should be in /var/lib/puppetdb which is the default location in the installed package.
/var/lib is for Variable state information according to the FHS.

It is also impossible to override this without editing the params class please make it editible or change the default to a more sensible location.

Thanks

**Comment by h0tw1r3** [comment]
Embedded database is no longer supported.
