### ISSUE TITLE
Service {'puppetdb': } on Ubuntu 12.04 will try to start the service even though it seems to be up

### ISSUE THREAD

**Issue by kbarber** [puppetlabs/puppetlabs-puppetdb#57]
While working on #54 I found that specifically on Ubuntu 12.04 that the second run after PuppetDB is installed and running is convinced the service is not running, and tries to start it again.

This occurs even though ps auxw, service puppetdb status and even puppet resource service puppetdb show it to be running right before the puppet run. I spent a day trying to track it down with no luck, but it still exists. The workaround for me was to run the second puppet run with --debug, which alludes to an attenuation solution - however putting in sleeps beforehand do not work. Its a strange one, but needs fixing none-the-less.

**Comment by h0tw1r3** [comment]
Stale issue, platform no longer supported.
