### ISSUE TITLE
puppetdb postgresql-server version parameter

### ISSUE THREAD

**Issue by aboe76** [puppetlabs/puppetlabs-puppetdb#75]
I would like to be able to set the postgresql version that would be used by puppetdb
At the moment puppetdb module just calls postgresql::server and
installs the default postgresql server for the os.

I would like to be able to say postgresqlversion = 9.1 and
puppetdb would call:

```
class { 'postgresql':
  $version = $postgresqlversion_from_puppetdb
}->
class { 'postgresql::server': }
```

**Comment by h0tw1r3** [comment]
Ability to set the postgres_version as a parameter on the base class was added in #162
