### ISSUE TITLE
Puppetdb module always trigger a change event even when postgress was installed and configured successfully in previous iterations

### ISSUE THREAD

**Issue by juasiepo** [puppetlabs/puppetlabs-puppetdb#83]
The following can be seen on my puppet dashboard logs:
"
Exec[validate postgres connection for localhost/puppetdb](/etc/puppet/modules/postgresql/manifests/validate_db_connection.pp:82)
    Property    Message
    returns     executed successfully
"
This creates a change event in every puppet agent run, so the puppet dashboard will always be blue (instead of green) for the afected node.

Here you are the nodes.pp 
node 'puppetdb.example.com' inherits default {
  class { 'puppetdb': }
  class { 'puppetdb::master::config': }
}

**Comment by h0tw1r3** [comment]
Recently added workflow acceptance tests confirm this is no longer an issue.
